apiVersion: v1
kind: Service
metadata:
  name: {{ template "master.fullname" . }}
  labels:
    app: "{{ template "mariadb.name" . }}"
    component: "master"
    chart: {{ template "mariadb.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - name: mysql
    port: {{ .Values.service.port }}
    targetPort: mysql
  clusterIP: None    
  selector:
    app: "{{ template "mariadb.name" . }}"
    component: "master"
    release: "{{ .Release.Name }}"
